export const GENERAL_CROSS_QUOTES: string[] = [
  "There are three constants in life... change, choice and principles.",
  "You have to go through those mountains and valleys - because that's what life is: soul growth.",
  "Life is too short to worry about anything. You had better enjoy it because the next day promises nothing.",
  "Relax! Life is beautiful!",
  "Beginning today, treat everyone you meet as if they were going to be dead by midnight. Extend to them all the care, kindness and understanding you can muster, and do it with no thought of any reward. Your life will never be the same again.",
  "Remember your dreams and fight for them. You must know what you want from life. There is just one thing that makes your dream become impossible: the fear of failure.",
  "I like nonsense; it wakes up the brain cells.",
  "If you take no risks, you will suffer no defeats. But if you take no risks, you win no victories.",
  "You have to take risks. We will only understand the miracle of life fully when we allow the unexpected to happen.",
  "You're only given a little spark of madness. You mustn't lose it.",
  "The longer you hang in there, the greater the chance that something will happen in your favor. No matter how hard it seems, the longer you persist, the more likely your success.",
  "Forgiveness for one's self is the only way we can keep going through life and give ourselves the best chance at being the best people we can be.",
  "It's choice - not chance - that determines your destiny.",
  "A wise man turns chance into good fortune.",
  "The risk of a wrong decision is preferable to the terror of indecision.",
  "Anytime we step out boldly to make changes, we take a chance that we might fail. But the only way to get better is to try.",
  "A good plan violently executed now is better than a perfect plan executed next week.",
  "Random chance plays a huge part in everybody's life.",
  "Consult not your fears but your hopes and your dreams. Think not about your frustrations, but about your unfulfilled potential. Concern yourself not with what you tried and failed in, but with what it is still possible for you to do.",
  "Problems can be experienced as... a chance for renewal rather than stress.",
  "The great thing about getting older is that you get a chance to tell the people in your life who matter what they mean to you.",
  "We must overcome the notion that we must be regular... it robs you of the chance to be extraordinary and leads you to the mediocre.",
  "It's important to give it all you have while you have the chance.",
  "Luck always favors the brave.",
  "You only get one chance at life and you have to grab it boldly.",
  "Great deeds are usually wrought at great risks.",
  "Our lives improve only when we take chances - and the first and most difficult risk we can take is to be honest with ourselves.",
  "You never say never. There's always a chance to do things in the future.",
  "I'm all about taking chances. You have to ask yourself, if you're not taking any chances, are you actually even living?",
  "Determination, energy, and courage appear spontaneously when we care deeply about something. We take risks that are unimaginable in any other context.",
  "One chance is all you need.",
  "I believe in taking chances and living your life. Sometimes doors open and others close and you have to figure out which one you're going to take. I'm always for the one that's challenging.",
  "Everything existing in the universe is the fruit of chance and necessity.",
  "If you want to conquer fear, don't sit home and think about it. Go out and get busy.",
  "At the end of the day, you are solely responsible for your success and your failure. And the sooner you realize that, you accept that, and integrate that into your work ethic, you will start being successful.",
  "No matter what kind of challenges or difficulties or painful situations you go through in your life, we all have something deep within us that we can reach down and find the inner strength to get through them.",
  "You have power over your mind - not outside events. Realize this, and you will find strength.",
  "Shallow men believe in luck. Strong men believe in cause and effect.",
  "Where there is no struggle, there is no strength.",
  "Believe in yourself, and the rest will fall into place. Have faith in your own abilities, work hard, and there is nothing you cannot accomplish.",
  "We are all born ignorant, but one must work hard to remain stupid.",
  "Youth is the gift of nature, but age is a work of art.",
  "When something is important enough, you do it even if the odds are not in your favor.",
  "Excellence is not a skill, it's an attitude.",
  "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.",
  "If you fell down yesterday, stand up today.",
  "We all have big changes in our lives that are more or less a second chance.",
  "Living at risk is jumping off the cliff and building your wings on the way down.",
  "Just keep taking chances and having fun.",
  "It is better to know some of the questions than all of the answers.",
  "There are three ingredients in the good life: learning, earning and yearning.",
  "If you live long enough, you'll make mistakes. But if you learn from them, you'll be a better person. It's how you handle adversity, not how it affects you. The main thing is never quit, never quit, never quit.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "No matter what people tell you, words and ideas can change the world.",
  "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.",
  "Life is short, and we should respect every moment of it.",
  "The way to get started is to quit talking and begin doing.",
  "Every man dies. Not every man really lives.",
  "Life doesn't require that we be the best, only that we try our best.",
  "It is easy to sit up and take notice. What is difficult is getting up and taking action.",
  "I think in this life it's important to be kind, be thankful, and always be creative.",
  "It is not what happens to you that matters, but what you do about it that makes the difference.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "Life is like a ten speed bicycle. Most of us have gears we never use.",
  "Sometimes we need to remind ourselves that thankfulness is indeed a virtue.",
  "One thing I've learned about life is that if you really let go, it's just a joy ride.",
  "Life is difficult for everyone; everyone has bad days. Everyone has trouble in their life, because it doesn't matter how rich you are: Sickness and trouble and worry and love, these things will mess with you at every level of life.",
  "20 years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.",
  "If the only tool you have is a hammer, you tend to see every problem as a nail.",
  "Never take anything for granted.",
  "Of all the characteristics needed for both a happy and morally decent life, none surpasses gratitude.",
  "There's no happier person than a truly thankful, content person.",
  "So many people live within unhappy circumstances and yet will not take the initiative to change their situation because they are conditioned to a life of security, conformity, and conservation.",
  "If in our daily life we can smile, if we can be peaceful and happy, not only we, but everyone will profit from it. This is the most basic kind of peace work.",
  "Forgiveness is not always easy. At times, it feels more painful than the wound we suffered, to forgive the one that inflicted it. And yet, there is no peace without forgiveness.",
  "There is no real beauty without some slight imperfection.",
  "Life itself is the most wonderful fairy tale.",
  "Live and work but do not forget to play, to have fun in life and really enjoy it.",
  "We do not remember days, we remember moments.",
  "Life is like a landscape. You live in the midst of it but can describe it only from the vantage point of distance.",
  "The only real things in life is the unexpected things. Everything else is just an illusion.",
  "Be grateful for what you have and stop complaining - it bores everybody else, does you no good, and doesn't solve any problems.",
  "When you rise in the morning, give thanks for the light, for your life, for your strength. Give thanks for your food and for the joy of living.",
  "I enjoy life when things are happening. I don't care if it's good things or bad things. That means you're alive.",
  "Only those who have learned the power of sincere and selfless contribution experience life's deepest joy: true fulfillment.",
  "I'm not saying that everyone should swim with sharks, but sometimes you have to jump over your own shadow in order to learn something that you will never forget for the rest of your life.",
  "I want to be as gracious and thankful as I can because it has been a long road.",
  "Whatever we are waiting for - peace of mind, contentment, grace, the inner awareness of simple abundance - it will surely come to us, but only when we are ready to receive it with an open and grateful heart.",
  "Life is hard, but there are moments, sometimes hours - and, if you're really lucky, full days - where everything feels just right.",
  "I'll tell you what I'm grateful for, and that's the clarity of understanding that the most important things in life are health, family and friends, and the time to spend on them.",
  "Sometimes it's the smallest decisions that can change your life forever.",
  "In everyone's life, at some time, our inner fire goes out. It is then burst into flame by an encounter with another human being. We should all be thankful for those people who rekindle the inner spirit.",
  "Be thankful for what you have; you'll end up having more.",
  "Let me encourage you to get up every day and focus on what you do have in life. Be thankful for the blessings of the little things, even when you don't get what you expect.",
  "Life's tragedy is that we get old too soon and wise too late.",
  "The only disability in life is a bad attitude.",
  "Memories are the best things in life, I think.",
  "You are not important because of how long you live, you are important because of how effective you live.",
  "Life is a game and true love is a trophy.",
  "The more sand has escaped from the hourglass of our life, the clearer we should see through it.",
  "I think our life is a journey, and we make mistakes, and it's how we learn from those mistakes and rebound from those mistakes that sets us on the path that we're meant to be on.",
  "Life isn't about finding yourself. Life is about creating yourself.",
  "He who is not courageous enough to take risks will accomplish nothing in life.",
  "However difficult life may seem, there is always something you can do and succeed at.",
  "Into each life some rain must fall.",
  "When you are grateful - when you can see what you have - you unlock blessings to flow in your life.",
  "Bad things do happen; how I respond to them defines my character and the quality of my life.",
  "Everyone has a purpose in life and a unique talent to give to others.",
  "Happiness is being content with what you have, living in freedom and liberty, having a good family life and good friends.",
  "Never give up. There are always tough times, regardless of what you do in anything in life. Be able to push through those times and maintain your ultimate goal.",
  "The game of life is a lot like football. You have to tackle your problems, block your fears, and score your points when you get the opportunity.",
  "Simply enjoy life and the great pleasures that come with it.",
  "All life demands struggle. Those who have everything given to them become lazy, selfish, and insensitive to the real values of life.",
  "Unlike a drop of water which loses its identity when it joins the ocean, man does not lose his being in the society in which he lives.",
  "The purpose of human life is to serve, and to show compassion and the will to help others.",
  "Visualize this thing that you want, see it, feel it, believe in it. Make your mental blue print, and begin to build.",
  "Age is just a number. Life and aging are the greatest gifts that we could possibly ever have.",
  "If you go around being afraid, you're never going to enjoy life. You have only one chance, so you've got to have fun.",
  "Change your life today. Don't gamble on the future, act now, without delay.",
  "The most important thing in communication is hearing what isn't said.",
  "Gratitude unlocks the fullness of life. It turns what we have into enough, and more.",
  "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.",
  "It's amazing. Life changes very quickly, in a very positive way, if you let it.",
  "Falling in love consists merely in uncorking the imagination and bottling the common sense.",
  "You can't expect to hit the jackpot if you don't put a few nickels in the machine.",
  "The reason people find it so hard to be happy is that they always see the past better than it was, the present worse than it is, and the future less resolved than it will be.",
  "At the end of the day, you are solely responsible for your success and your failure. And the sooner you realize that, you accept that, and integrate that into your work ethic, you will start being successful. As long as you blame others for the reason you aren't where you want to be, you will always be a failure.",
  "Of all the characteristics needed for both a happy and morally decent life, none surpasses gratitude. Grateful people are happier, and grateful people are more morally decent.",
  "So many people live within unhappy circumstances and yet will not take the initiative to change their situation because they are conditioned to a life of security, conformity, and conservation, all of which may appear to give one peace of mind, but in reality, nothing is more damaging to the adventurous spirit.",
  "When you rise in the morning, give thanks for the light, for your life, for your strength. Give thanks for your food and for the joy of living. If you see no reason to give thanks, the fault lies in yourself.",
  "I'm not saying that everyone should swim with sharks, but sometimes you have to jump over your own shadow in order to learn something that you will never forget for the rest of your life. Then you know you can conquer your fears.",
  "Bad things do happen; how I respond to them defines my character and the quality of my life. I can choose to sit in perpetual sadness, immobilized by the gravity of my loss, or I can choose to rise from the pain and treasure the most precious gift I have - life itself.",
  "All life demands struggle. Those who have everything given to them become lazy, selfish, and insensitive to the real values of life. The very striving and hard work that we so constantly try to avoid is the major building block in the person we are today.",
  "Unlike a drop of water which loses its identity when it joins the ocean, man does not lose his being in the society in which he lives. Man's life is independent. He is born not for the development of the society alone, but for the development of his self.",
  "Gratitude unlocks the fullness of life. It turns what we have into enough, and more. It turns denial into acceptance, chaos to order, confusion to clarity. It can turn a meal into a feast, a house into a home, a stranger into a friend.",
  "Problems can be experienced as a chance for renewal rather than stress.",
  "Gratitude unlocks the fullness of life. It turns what we have into enough, and more. It turns denial into acceptance, chaos to order, confusion to clarity.",
  "Luck always favors the brave",
  "Anytime we step out boldly to make changes, we take a chance that we might fail. But the only way to get better is to try",
  "The way to get started is to quit talking and begin doing",
  "It is easy to sit up and take notice, What is difficult is getting up and taking action.",
  "20 years from now you will be more disappointed by the things that you didnÃÂ¢ÃÂÃÂt do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails.Explore. Dream. Discover.",
  "The reason people find it so hard to be happy is that they always see the past better than it was, the present worse than it is, and the future less resolved than it will be",
  "Because your own strength is unequal to the task, do not assume that it is beyond the powers of man; but if anything is within the powers and province of man, believe that it is within your own compass also.",
  "There are two ways of exerting one's strength: one is pushing down, the other is pulling up.",
  "We draw our strength from the very despair in which we have been forced to live. We shall endure.",
  "It's so easy to be there when it's all sunshine, but it really takes strength and courage to be there for each other during the dark times.",
  "It takes strength to make your way through grief, to grab hold of life and let it pull you forward.",
  "We will naturally pursue our goals on the strength of our own resources, skills and enterprise. But, we know that we will be more successful when we do this in partnership with the world.",
  "Wisdom is the knowledge of good and evil, not the strength to choose between the two.",
  "Trust is the most important part of a relationship, closely followed by communication. I think that if you have those two things, everything else falls into place - your affection, your emotional connection.",
  "There are ups and downs, but whatever happens, you have to trust and believe in yourself.",
  "Trust your own instincts, go inside, follow your heart. Right from the start. go ahead and stand up for what you believe in. As I've learned, that's the path to happiness.",
  "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.",
  "Leadership contains certain elements of good management, but it requires that you inspire, that you build durable trust. For an organization to be not just good but to win, leadership means evoking participation larger than the job description, commitment deeper than any job contract's wording.",
  "Loyalty and devotion lead to bravery. Bravery leads to the spirit of self-sacrifice. The spirit of self-sacrifice creates trust in the power of love.",
  "Trust your passion. Believe in your dream.",
  "Advice number one: listen to your gut - it's never gonna lead you wrong. Number two: trust yourself. The root of everything is self-belief.",
  "Be true to yourself, stay focused and stay you, take advice from other folks, use what you can, but never mind what is not for you. For the most part, trust yourself and believe in what you are doing.",
  "If people like you, they'll listen to you, but if they trust you, they'll do business with you.",
  "To have faith is to trust yourself to the water. When you swim you don't grab hold of the water, because if you do you will sink and drown. Instead you relax, and float.",
  "Age appears to be best in four things; old wood best to burn, old wine to drink, old friends to trust, and old authors to read.",
  "Trust should be the basis for all our moral training.",
  "Trust and belief are two prime considerations. You must not allow yourself to be opinionated.",
  "You have got to discover you, what you do, and trust it.",
  "The more you trust your intuition, the more empowered you become, the stronger you become, and the happier you become.",
  "I believe fundamental honesty is the keystone of business.",
  "Depend upon yourself. Make your judgement trustworthy by trusting it. You can develop good judgement as you do the muscles of your body - by judicious, daily exercise. To be known as a man of sound judgement will be much in your favor.",
  "Trust in what you love, continue to do it, and it will take you where you need to go.",
  "One of the common failings among honorable people is a failure to appreciate how thoroughly dishonorable some other people can be, and how dangerous it is to trust them.",
  "Confidence is that feeling by which the mind embarks in great and honorable courses with a sure hope and trust in itself.",
  "Mature love is composed and sustaining; a celebration of commitment, companionship, and trust.",
  "Trust not yourself, but your defects to know, make use of every friend and every foe.",
  "Knowing others is wisdom, knowing yourself is Enlightenment.",
  "Nothing that you have not given away will ever be really yours.",
  "A long habit of not thinking a thing wrong gives it a superficial appearance of being right.",
  "Genius is one percent inspiration and ninety-nine percent perspiration.",
  "The greater danger for most of us lies not in setting our aim too high and falling short; but in setting our aim too low, and achieving our mark.",
  "Always seek out the seed of triumph in every adversity.",
  "We are what our thoughts have made us; so take care about what you think. Words are secondary. Thoughts live; they travel far.",
  "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.",
  "A little knowledge that acts is worth infinitely more than much knowledge that is idle.",
  "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.",
  "Discipline is the bridge between goals and accomplishment.",
  "Reality is merely an illusion, albeit a very persistent one.",
  "We gain the strength of the temptation we resist.",
  "It is a characteristic of wisdom not to do desperate things.",
  "Honesty is the best policy.",
  "One's philosophy is not best expressed in words; it is expressed in the choices one makes... and the choices we make are ultimately our responsibility.",
  "The teacher who is indeed wise does not bid you to enter the house of his wisdom but rather leads you to the threshold of your mind.",
  "Wisdom begins in wonder.",
  "Wisdom stands at the turn in the road and calls upon us publicly, but we consider it false and despise its adherents.",
  "Beware of false knowledge; it is more dangerous than ignorance.",
  "He who lives in harmony with himself lives in harmony with the universe.",
  "Who is wise in love, love most, say least.",
  "Climb the mountains and get their good tidings.",
  "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.",
  "Turn your wounds into wisdom.",
  "Wisdom is found only in truth.",
  "When written in Chinese, the word 'crisis' is composed of two characters. One represents danger and the other represents opportunity.",
  "The three great essentials to achieve anything worth while are: Hard work, Stick-to-itiveness, and Common sense.",
  "A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them.",
  "If you talk to a man in a language he understands, that goes to his head. If you talk to him in his language, that goes to his heart.",
  "Commitment is an act, not a word.",
  "The truth is not for all men, but only for those who seek it.",
  "Memory is the mother of all wisdom.",
  "Freedom is never more than one generation away from extinction. We didn't pass it to our children in the bloodstream. It must be fought for, protected, and handed on for them to do the same.",
  "Necessity is blind until it becomes conscious. Freedom is the consciousness of necessity.",
  "It is difficult to free fools from the chains they revere.",
  "Expose yourself to your deepest fear; after that, fear has no power, and the fear of freedom shrinks and vanishes. You are free.",
  "The more decisions that you are forced to make alone, the more you are aware of your freedom to choose.",
  "I believe firmly that in making ethical decisions, man has the prerogative of true freedom of choice.",
  "Change does not roll in on the wheels of inevitability, but comes through continuous struggle. And so we must straighten our backs and work for our freedom. A man can't ride you unless your back is bent.",
  "Freedom is what you do with what's been done to you.",
  "Freedom is from within.",
  "Freedom is the recognition of necessity.",
  "One cool judgment is worth a thousand hasty counsels. The thing to do is to supply light and not heat.",
  "To act coolly, intelligently and prudently in perilous circumstances is the test of a man - and also a nation.",
  "He who keeps his cool best wins.",
  "Being uncool is being pretty much the coolest you can be.",
  "The happiness of your life depends upon the quality of your thoughts: therefore, guard accordingly, and take care that you entertain no notions unsuitable to virtue and reasonable nature.",
  "Some cause happiness wherever they go; others whenever they go.",
];
